// Generated by CoffeeScript 1.3.3

/*
Kinetic plugin for Knockout. Version 0.1.0
*/


(function() {
  var __hasProp = {}.hasOwnProperty;

  (function(factory) {
    if (typeof require === 'function' && typeof exports === 'object' && typeof module === 'object') {
      return factory(require('knockout'), exports);
    } else if (typeof define === 'function' && define['amd']) {
      return define(['knockout', 'exports'], factory);
    } else {
      return factory(ko, ko.kinetic = {});
    }
  })(function(ko, exports) {
    var bindingName, ctor, expandConfig, makeBindingHandler, nodeFactory, nodeType;
    expandConfig = function(config) {
      var key, result, temp, value;
      if (!config) {
        return {};
      }
      temp = typeof config === 'function' ? config() : config;
      if (!(temp instanceof Object)) {
        return temp;
      }
      result = {};
      for (key in temp) {
        if (!__hasProp.call(temp, key)) continue;
        value = temp[key];
        result[key] = expandConfig(value);
      }
      return result;
    };
    makeBindingHandler = function(nodeFactory) {
      return {
        init: function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
          var config, innerContext, node;
          config = expandConfig(valueAccessor());
          node = nodeFactory(config, element.parentNode);
          innerContext = bindingContext.extend({
            parentNode: node
          });
          ko.applyBindingsToDescendants(innerContext, element);
          if (bindingContext.parentNode) {
            bindingContext.parentNode.add(node);
          }
          if (element.style) {
            element.style.display = 'none';
          }
          element._kk = node;
          return {
            controlsDescendantBindings: true
          };
        },
        update: function(element, valueAccessor) {
          var config, key, node, updated, value;
          node = element._kk;
          config = expandConfig(valueAccessor());
          updated = false;
          for (key in config) {
            value = config[key];
            if (value === node.attrs[key]) {
              continue;
            }
            node.attrs[key] = value;
            updated = true;
          }
          if (updated && node.getParent()) {
            return node.getLayer().draw();
          }
        }
      };
    };
    for (nodeType in Kinetic) {
      ctor = Kinetic[nodeType];
      if (!(typeof ctor === 'function')) {
        continue;
      }
      nodeFactory = (function(nodeType, ctor) {
        if (nodeType === 'Stage') {
          return function(config, parent) {
            config['container'] = parent;
            return new ctor(config);
          };
        } else {
          return function(config) {
            return new ctor(config);
          };
        }
      })(nodeType, ctor);
      bindingName = "Kinetic." + nodeType;
      ko.bindingHandlers[bindingName] = makeBindingHandler(nodeFactory);
      ko.virtualElements.allowedBindings[bindingName] = true;
    }
  });

}).call(this);
